version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_0506_prod156015Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_0506_prod156015.integrations:varTest
  packages:
  - name: Kvv_0506_prod156015Project
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.2062
